(() => {
  'use strict';
  const VERSION = '2.3';
  const KEY = 'shiji-reality-calibration-v2.3';
  const LEGACY_KEYS = ['shiji-reality-calibration-v2', 'shiji-reality-calibration-v1'];
  const isWeChat = /MicroMessenger/i.test(navigator.userAgent);
  const OPTIONS = {
    focus: [['A','更清楚地认识自己的特点与行为习惯'],['B','理解自己的优势、能力与发挥条件'],['C','事业、学习或专业发展'],['D','财富、资源与投入回报'],['E','合作、沟通与个人边界'],['F','亲密关系或家庭互动'],['G','压力、情绪与恢复方式'],['H','行动力、持续性与生活节奏'],['I','当前正在经历的选择或阶段变化']],
    concern: [['A','我不确定自己的方向，或适合做什么'],['B','我知道方向，但能力或资源跟不上'],['C','我容易在某件事上反复卡住、推进不动'],['D','我在关系或合作里总觉得哪里别扭'],['E','我常常情绪内耗或自我怀疑，想搞清楚自己为什么会这样']],
    positive: [['A','思路清楚，善于分析和整理'],['B','执行力强，能够把事情推进'],['C','可靠，答应的事情会尽量完成'],['D','独立，有自己的判断'],['E','善于表达、讲解或影响他人'],['F','能理解他人，愿意照顾关系'],['G','面对变化或压力时反应较快'],['H','有耐心，能够长期深入一件事']],
    friction: [['A','想得太多，决定得比较慢'],['B','标准较高，对自己或他人要求较多'],['C','表达直接，容易忽略对方的感受'],['D','不容易说出自己的真实需要'],['E','容易承担过多，不太会拒绝'],['F','坚持自己的判断，不容易被说服'],['G','遇到冲突时倾向暂时回避'],['H','在意细节，容易影响整体推进']],
    complex: [['A','先理解整体结构和问题原理'],['B','先收集足够的信息，再作判断'],['C','先确定目标、标准和风险边界'],['D','先与相关的人讨论，补充不同视角'],['E','先做一个小范围尝试，再根据结果调整'],['F','先开始行动，在过程中逐步理清'],['G','根据过往经验迅速判断，再检查是否需要修正']],
    invest: [['A','能够自己决定方向和方式'],['B','能感受到自己不断掌握和进步'],['C','能做出具体、看得见的结果'],['D','得到认可、信任或积极反馈'],['E','对他人或某件重要的事有价值'],['F','能与认同的人共同完成'],['G','有清楚的规则、预期和稳定感'],['H','有新鲜感、变化或探索空间'],['I','有明确的现实回报'],['J','能表达自己的观点或创造新的东西']],
    lose: [['A','长期看不到进展或结果'],['B','缺少自主空间，处处受到限制'],['C','目标和标准反复变化'],['D','任务重复，缺少新的挑战'],['E','责任很多，但资源或权限不足'],['F','人际关系消耗过大'],['G','努力长期得不到认可或回报'],['H','不认同事情本身的意义'],['I','需要长期独自承担，缺少支持']],
    pressure: [['A','立即分析问题并寻找解决办法'],['B','反复思考细节，暂时难以停止'],['C','先压住感受，把该做的事情完成'],['D','暂时退出现场，减少交流和刺激'],['E','找信任的人讨论或寻求支持'],['F','通过运动、娱乐、睡眠等方式转移注意'],['G','情绪会先明显表现出来，之后再处理问题'],['H','身体会先出现疲惫、紧绷、睡眠或食欲变化']],
    recovery: [['A','找人聊'],['B','运动'],['C','睡眠／休息'],['D','独处／离开现场'],['E','娱乐转移'],['F','其他']],
    relationship: [['A','先把事实、逻辑和责任讲清楚'],['B','先了解彼此的感受和真实需要'],['C','尽快寻找双方都能接受的方案'],['D','先减少冲突，等情绪稳定后再谈'],['E','先反思自己是否需要承担责任'],['F','明确表达自己的立场和边界'],['G','希望对方主动理解，不太容易直接开口'],['H','根据关系的重要程度决定坚持还是退让'],['I','寻求可信任的第三方帮助梳理']]
  };
  const DYNAMIC = {
    A:['特点与反复模式','最近最想改变的一个反复模式，最常在什么情境下出现？',[['A','压力下'],['B','关系中'],['C','工作时'],['D','独处时']]],
    B:['优势与能力','你最希望被看见或进一步发挥的能力，目前最容易卡在哪里？',[['A','机会'],['B','环境'],['C','信心'],['D','资源']]],
    C:['事业、学习或专业发展','你目前最想推进的事，卡点更接近哪一种？',[['A','方向'],['B','能力'],['C','行动'],['D','资源'],['E','关系']]],
    D:['财富、资源与投入回报','你最想理解的，更接近哪一种？',[['A','价值创造'],['B','收入来源'],['C','资源分配'],['D','投入回报']]],
    E:['合作、沟通与边界','最近最消耗你的合作或沟通，问题更接近哪一种？',[['A','沟通不清'],['B','边界不明'],['C','责任不均'],['D','目标不一']]],
    F:['亲密关系或家庭互动','目前最常重复的关系摩擦，更接近哪一种？',[['A','表达'],['B','边界'],['C','责任'],['D','期待']]],
    G:['压力、情绪与恢复','最近最常消耗你的情境，更接近哪一种？',[['A','工作'],['B','关系'],['C','自我要求'],['D','不确定']]],
    H:['行动力、持续性与生活节奏','你最常在哪个环节卡住？',[['A','开始'],['B','持续'],['C','完成'],['D','停止'],['E','中断后重启']]],
    I:['当前选择或阶段变化','你目前最难判断的，更接近哪一种？',[['A','方向'],['B','取舍'],['C','时机'],['D','风险']]]
  };
  const STEPS = [['01','关注重点','你最希望这份报告重点回应什么？'],['02','内外视角','现在的你，和别人眼中的你'],['03','现实经历','一件能够代表你的真实经历'],['04','判断起点','面对复杂或不确定的问题，你通常从哪里开始？'],['05','动力条件','什么让你愿意投入，又是什么在消耗动力？'],['06','压力恢复','压力来临时，你最先怎样反应，又怎样恢复？'],['07','关系边界','重要关系出现分歧时，你通常怎样处理？'],['08','经历转折','哪段经历改变了你对自己的认识？']];
  const blank = {focus:[],primaryFocus:'',concernType:'',concernText:'',dynamicType:'',dynamicText:'',selfNow:'',positive:[],friction:[],representativeSituation:'',representativeAction:'',representativeResult:'',complex:[],complexCase:'',invest:[],lose:[],investExample:'',pressure:[],pressureTrigger:'',recovery:[],recoveryOther:'',relationship:[],relationshipNeed:'',turningPoints:''};
  const app = document.getElementById('app');
  let answers = load(), screen = 'welcome', step = 0, notice = '';

  function validCodes(value, options) { const allowed = new Set(options.map(x => x[0])); return Array.isArray(value) ? value.filter(x => allowed.has(x)) : []; }
  function migrate(raw) {
    const focus = validCodes(raw.focus, OPTIONS.focus), primaryFocus = focus.includes(raw.primaryFocus) ? raw.primaryFocus : '';
    return {...blank,focus,primaryFocus,concernText:raw.focusQuestion||'',dynamicText:raw.dynamicAnswer||'',selfNow:raw.selfNow||raw.selfThree||'',positive:validCodes(raw.positive,OPTIONS.positive),friction:validCodes(raw.friction,OPTIONS.friction),representativeSituation:raw.representativeExperience||raw.abilityEvidence||'',complex:validCodes(raw.complex,OPTIONS.complex),complexCase:raw.complexCase||'',invest:validCodes(raw.invest,OPTIONS.invest),lose:validCodes(raw.lose,OPTIONS.lose),investExample:raw.investExample||'',pressure:validCodes(raw.pressure,OPTIONS.pressure),pressureTrigger:raw.pressureExperience||'',relationship:validCodes(raw.relationship,OPTIONS.relationship),relationshipNeed:raw.relationshipNeed||'',turningPoints:raw.turningPoints||''};
  }
  function load() {
    try {
      const current = JSON.parse(localStorage.getItem(KEY)||'null'); if (current) return {...blank,...current};
      for (const key of LEGACY_KEYS) { const old = JSON.parse(localStorage.getItem(key)||'null'); if (old) { const migrated=migrate(old); localStorage.setItem(KEY,JSON.stringify(migrated)); return migrated; } }
    } catch (_) {}
    return {...blank};
  }
  function save(){localStorage.setItem(KEY,JSON.stringify(answers));}
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
  function optionLabel(items,code){return (items.find(x=>x[0]===code)||['',code])[1];}
  function answeredCount(){return Object.values(answers).filter(v=>Array.isArray(v)?v.length:String(v||'').trim()).length;}
  function choices(name,max,showMax=true){const selected=answers[name]||[];return `<div class="choice-block"><div class="choice-count">已选择 ${selected.length}${showMax?`/${max}`:' 项'}</div><div class="option-list">${OPTIONS[name].map(([code,text])=>{const active=selected.includes(code),disabled=!active&&selected.length>=max;return `<button type="button" class="option-card ${active?'active':''}" data-choice="${name}" data-code="${code}" data-max="${max}" aria-pressed="${active}" ${disabled?'disabled aria-disabled="true"':''}><span class="option-letter">${code}</span><span>${text}</span><span class="check">${active?'✓':''}</span></button>`;}).join('')}</div></div>`;}
  function single(name,items){const selected=answers[name]||'';return `<div class="single-list">${items.map(([code,text])=>`<button type="button" class="option-card single-option ${selected===code?'active':''}" data-single="${name}" data-code="${code}" aria-pressed="${selected===code}"><span class="radio-dot"></span><span>${text}</span><span class="check">${selected===code?'✓':''}</span></button>`).join('')}</div>`;}
  function field(name,title,hint='',optional=false,rows=5){const value=answers[name]||'',guidance=optional?`如果愿意，建议尽量补充；如果不想回答或感到不舒服，也可以不填。${hint?` ${hint}`:''}`:hint;return `<label class="text-field"><span class="field-label">${title}${optional?'<em>选填</em>':''}</span>${guidance?`<span class="field-hint">${guidance}</span>`:''}<textarea rows="${rows}" data-field="${name}" placeholder="请写下真实经历或感受……">${esc(value)}</textarea><span class="char-count">${String(value).trim().length} 字</span></label>`;}
  function sub(title,note=''){return `<div class="subheading"><h2>${title}</h2>${note?`<p>${note}</p>`:''}</div>`;}
  function primary(){if(!answers.focus.length)return '';return `<div class="primary-focus"><h2>其中，你最希望重点展开的一项是：</h2><p>单选。它决定下方显示哪一道追问。</p><div class="primary-pills">${answers.focus.map(code=>`<button type="button" class="primary-pill ${answers.primaryFocus===code?'active':''}" data-primary="${code}"><i></i><span>${optionLabel(OPTIONS.focus,code)}</span></button>`).join('')}</div></div>`;}
  function dynamic(){const branch=DYNAMIC[answers.primaryFocus];if(!branch)return '';return `<div class="dynamic-section"><span class="dynamic-sign">根据“${optionLabel(OPTIONS.focus,answers.primaryFocus)}”显示</span>${sub(`追问｜${branch[0]}`,`${branch[1]} 单选。`)}${single('dynamicType',branch[2])}${field('dynamicText','补充','',true,3)}</div>`;}
  function stepBody(i){
    if(i===0)return `<p class="helper">多选，最多选择2项。整题也可以跳过。</p>${choices('focus',2)}${primary()}${sub('你目前最想弄清楚的问题，更接近哪一种？','单选。如果都不太像，选最接近的一个，再在下方补充。')}${single('concernType',OPTIONS.concern)}${field('concernText','补充你的真实困惑','',true,3)}${dynamic()}`;
    if(i===1)return `${field('selfNow','你怎样理解现在的自己？','如果暂时不介绍年龄、职业和家庭身份，你会用哪一句话描述现在的自己？',false,3)}${sub('别人较常肯定你什么？','多选，最多选择3项。')}${choices('positive',3)}${sub('出现摩擦时，别人较常怎样评价你？','多选，最多选择2项。')}${choices('friction',2)}`;
    if(i===2)return `<p class="helper">请回想一件近两年真实发生、让你有印象的事，写下你还记得的部分。</p>${field('representativeSituation','当时需要处理什么','',false,4)}${field('representativeAction','你做了什么','',false,4)}${field('representativeResult','结果如何','',false,4)}`;
    if(i===3)return `<p class="helper">多选，最多选择2项。</p>${choices('complex',2)}${field('complexCase','最近一次真实案例','最近一次遇到复杂问题时，你最先做了什么？',true,4)}`;
    if(i===4)return `${sub('让你更愿意投入的条件','多选，最多选择3项。')}${choices('invest',3)}${sub('让你容易失去动力的条件','多选，最多选择2项。')}${choices('lose',2)}${field('investExample','一个愿意持续投入的例子','即使没人催促，你也愿意持续做什么？',true,4)}`;
    if(i===5)return `${sub('最先出现的反应','多选，最多选择2项。')}${choices('pressure',2)}${field('pressureTrigger','什么事情触发了压力？','请回想一次近期压力经历。',true,4)}${sub('什么方式真正帮助你恢复？','多选。')}${choices('recovery',6,false)}${answers.recovery.includes('F')?field('recoveryOther','其他恢复方式','',true,3):''}`;
    if(i===6)return `<p class="helper">这里的“重要关系”可以是伴侣、家人、朋友或长期合作伙伴。多选，最多选择2项。</p>${choices('relationship',2)}${field('relationshipNeed','关系中，你最难直接表达的需要是什么？','不确定时可以跳过。',true,3)}`;
    return `<p class="helper">选填。它可以是一段关系、一次选择、一项长期投入、一次成功或失败。</p>${field('turningPoints','哪段经历改变了你对自己的认识？','可以写：事情发生前你怎样理解自己，事情发生后什么认识发生了变化。',true,8)}`;
  }
  function prefix(){return (isWeChat?'<aside class="wechat-banner">微信内填写可能无法导出，请先点右上角「···」→「在浏览器打开」，再开始填写。</aside>':'')+(notice?`<div class="inline-notice" role="status">${esc(notice)}</div>`:'');}
  function render(preserve=false){const y=scrollY,p=prefix();if(screen==='welcome')app.innerHTML=`${p}<section class="card hero-card"><div class="hero-copy"><p class="kicker">从真实经验出发</p><h1>识己 · 经历与状态信息表</h1><p class="lead">你的经历、环境和选择，都会让报告更丰富、更贴近你。</p><div class="hero-quote">这不是心理测验，也没有需要迎合的正确答案。你写下的，也是一份日后仍可回看的觉察记录。</div><div class="notice-row"><span>6—10分钟</span><span>7道核心题</span><span>第1题含追问</span><span>1道选填深度题</span><span>本地保存</span></div><button class="primary hero-button" data-action="start">${answeredCount()?'继续填写':'开始填写'}<span>→</span></button><p class="privacy-note">全部内容都可以选择作答。完成度越高，报告的针对性越强；任何让你不舒服的问题都可以跳过。</p></div><div class="hero-visual"><img src="assets/hero-paper-path.jpg" alt="一页纸化为通向远山的青绿路径"><p class="image-caption">念起觉心、知深见己</p></div></section>`;else if(screen==='form'){const progress=Math.round((step+1)/STEPS.length*100);app.innerHTML=`${p}<section class="card form-card"><div class="progress-row"><span>Reality Calibration v${VERSION}</span><span>${step+1} / ${STEPS.length}</span></div><div class="progress-track"><span style="width:${progress}%"></span></div><p class="section-number">${STEPS[step][0]} · ${STEPS[step][1]}</p><h1>${STEPS[step][2]}</h1>${stepBody(step)}<div class="form-actions"><button class="text-button" data-action="previous">← 上一步</button><button class="primary" data-action="next">${step===STEPS.length-1?'检查并导出':'下一步'}<span>→</span></button></div><button class="skip-link" data-action="next">跳过这一题</button></section>`;}else app.innerHTML=`${p}<section class="card"><p class="kicker">提交前检查</p><h1>内容只由你决定是否导出</h1><p class="lead">你的回答仍只保存在当前设备。如需调整，可以返回修改；确认无误后，再保存并发送给识己。</p><div class="review-list">${STEPS.map(([n,t,q],i)=>`<button data-edit="${i}"><span>${n}</span><div><strong>${t}</strong><small>${q}</small></div><b>修改</b></button>`).join('')}</div><div class="export-panel"><p>请先检查并删除任何不想提交的内容。微信内可能无法保存文件，必要时请在系统浏览器中打开。</p><div class="export-actions"><button class="primary export-button" data-action="export">保存为本地 Markdown</button><button class="copy-button" data-action="copy-all">复制全部内容</button></div></div><div class="review-actions"><button class="text-button" data-action="last">← 返回修改</button><button class="danger-link" data-action="clear">清空本机草稿</button></div></section>`;scrollTo({top:preserve?y:0,behavior:preserve?'auto':'smooth'});}
  function lines(v,items){if(Array.isArray(v))return v.length?v.map(c=>`- ${c}. ${items?optionLabel(items,c):c}`).join('\n'):'（未填写）';return String(v||'').trim()||'（未填写）';}
  function markdown(){const date=new Intl.DateTimeFormat('zh-CN',{dateStyle:'long'}).format(new Date()),focus=answers.primaryFocus?`${answers.primaryFocus}. ${optionLabel(OPTIONS.focus,answers.primaryFocus)}`:'（未填写）',concern=answers.concernType?`${answers.concernType}. ${optionLabel(OPTIONS.concern,answers.concernType)}`:'（未填写）',branch=DYNAMIC[answers.primaryFocus],dynamicValue=branch&&answers.dynamicType?`${answers.dynamicType}. ${optionLabel(branch[2],answers.dynamicType)}`:'（未填写）';return ['# 识己 · 经历与状态信息表','',`填写日期：${date}`,`问卷版本：Reality Calibration v${VERSION}`,'','> 本文件由填写者主动导出，仅用于识己报告的现实校准。它不会改写已经独立完成并冻结的出生时空结构判断。','','## 1. 你最希望这份报告重点回应什么？','','### 关注主题（最多2项）','',lines(answers.focus,OPTIONS.focus),'','### 最希望重点展开','',focus,'','### 最想弄清楚的问题类型','',concern,'','### 对真实困惑的补充（选填）','',lines(answers.concernText),'',`### 追问｜${branch?branch[0]:'未指定重点主题'}`,'',branch?branch[1]:'（未填写）','',dynamicValue,'','### 追问补充（选填）','',lines(answers.dynamicText),'','## 2. 现在的你，和别人眼中的你','','### 你怎样理解现在的自己','',lines(answers.selfNow),'','### 别人较常肯定你什么（最多3项）','',lines(answers.positive,OPTIONS.positive),'','### 出现摩擦时，别人较常怎样评价你（最多2项）','',lines(answers.friction,OPTIONS.friction),'','## 3. 一件能够代表你的真实经历','','### 当时需要处理什么','',lines(answers.representativeSituation),'','### 你做了什么','',lines(answers.representativeAction),'','### 结果如何','',lines(answers.representativeResult),'','## 4. 面对复杂或不确定的问题，你通常从哪里开始？','','### 选择（最多2项）','',lines(answers.complex,OPTIONS.complex),'','### 最近一次真实案例（选填）','',lines(answers.complexCase),'','## 5. 什么让你愿意投入，又是什么在消耗动力？','','### 让你更愿意投入的条件（最多3项）','',lines(answers.invest,OPTIONS.invest),'','### 让你容易失去动力的条件（最多2项）','',lines(answers.lose,OPTIONS.lose),'','### 一个愿意持续投入的例子（选填）','',lines(answers.investExample),'','## 6. 压力来临时，你最先怎样反应，又怎样恢复？','','### 最先出现的反应（最多2项）','',lines(answers.pressure,OPTIONS.pressure),'','### 什么事情触发了压力（选填）','',lines(answers.pressureTrigger),'','### 真正帮助恢复的方式','',lines(answers.recovery,OPTIONS.recovery),'','### 其他恢复方式（选填）','',lines(answers.recoveryOther),'','## 7. 重要关系出现分歧时，你通常怎样处理？','','### 选择（最多2项）','',lines(answers.relationship,OPTIONS.relationship),'','### 最难直接表达的需要（选填）','',lines(answers.relationshipNeed),'','## 8. 哪段经历改变了你对自己的认识？（选填）','',lines(answers.turningPoints),'','---','','隐私提示：本表不应包含身份证号码、详细住址、账户信息、完整医疗记录或其他不必要的敏感资料。',''].join('\n');}
  function download(){if(isWeChat){notice='微信内无法导出，请点「···」→「在浏览器打开」，或复制链接到浏览器打开后再填。';render();return;}const date=new Date().toISOString().slice(0,10),file=new File([markdown()],`识己-经历与状态信息-${date}.md`,{type:'text/markdown;charset=utf-8'}),url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download=file.name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);notice='Markdown 文件已保存，可在浏览器下载中查看。';render();}
  async function copyAll(){try{await navigator.clipboard.writeText(markdown());notice='全部内容已复制，可粘贴到微信或备忘录发送。';}catch(_){notice='复制失败，请在系统浏览器中重试。';}render();}
  app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.choice){const n=b.dataset.choice,c=b.dataset.code,m=Number(b.dataset.max),arr=answers[n];answers[n]=arr.includes(c)?arr.filter(x=>x!==c):arr.length<m?[...arr,c]:arr;if(n==='focus'&&!answers.focus.includes(answers.primaryFocus)){answers.primaryFocus='';answers.dynamicType='';answers.dynamicText='';}save();render(true);return;}if(b.dataset.single){const n=b.dataset.single;answers[n]=answers[n]===b.dataset.code?'':b.dataset.code;save();render(true);return;}if(b.dataset.primary){answers.primaryFocus=b.dataset.primary;answers.dynamicType='';answers.dynamicText='';save();render(true);return;}if(b.dataset.edit!==undefined){step=Number(b.dataset.edit);screen='form';notice='';render();return;}const a=b.dataset.action;if(a==='start'){screen='form';notice='';}else if(a==='next'){if(step===0&&answers.focus.length&&!answers.primaryFocus){notice='请从已选主题中指定一项“最希望重点展开”。也可以取消所选主题后跳过本题。';render(true);return;}notice='';if(step<STEPS.length-1)step++;else screen='review';}else if(a==='previous'){notice='';if(step>0)step--;else screen='welcome';}else if(a==='last'){step=0;screen='form';notice='';}else if(a==='export'){download();return;}else if(a==='copy-all'){copyAll();return;}else if(a==='clear'&&confirm('确定清空当前设备上的全部填写内容吗？此操作无法撤销。')){answers={...blank};localStorage.removeItem(KEY);LEGACY_KEYS.forEach(k=>localStorage.removeItem(k));step=0;screen='welcome';notice='';}render();});
  app.addEventListener('input',e=>{const n=e.target.dataset.field;if(!n)return;answers[n]=e.target.value;save();const c=e.target.parentElement.querySelector('.char-count');if(c)c.textContent=`${e.target.value.trim().length} 字`;});
  render();
})();
